---
#driver:
#  name: vagrant
#  
#provisioner:
#  name: chef_solo
#
#platforms:
#  - name: ubuntu-12.04


driver:
  name: rackspace
  rackspace_username: josh768
  rackspace_api_key: 503865abac818518c4ec318a5cd7d969
  require_chef_omnibus: true
platforms:
  - name: ubuntu-12.04
rackspace_region: DFW
public_key_path: ~/.ssh/id_rsa.pub

suites:
  - name: default
    run_list: recipe[my_drupal_site::default]
    attributes:
